version: "3.2"
services:
  nginx:
    container_name: nginx
    build: './nginx/'
    ports: 
      - "80:80" # "the order is Host:Container "
      - "443:443"
    volumes:
      - certs:/etc/letsencrypt
      - certs-data:/data/letsencrypt
  # certbot:
  #   image: certbot/certbot
  #   volumes:
  #     - certs:/etc/letsencrypt
  #     - certs-data:/data/letsencrypt
  #   entrypoint:

volumes:
  certs:
  certs-data:

  # https://devsidestory.com/lets-encrypt-with-docker/#comment-3994814518
  # https://miki725.com/docker/crypto/2017/01/29/docker+nginx+letsencrypt.html