version: "3.2"
services:
  nginx:
    container_name: nginx
    build: './nginx/'
    ports: 
      - "80:80" # "the order is Host:Container "
      - "443:443"
    # volumes:
      # - ./data/certbot/conf:/etc/letsencrypt
      # - ./data/certbot/www:/var/www/certbot
      # - ./nginx.conf:/etc/nginx/conf.d/default.conf
      # - ./letsencrypt-site:/usr/share/nginx/html
  # https://github.com/blacklabelops-legacy/letsencrypt
  # certbot:
  #   image: certbot/certbot
  #   volumes:
  #     - ./data/certbot/conf:/etc/letsencrypt
  #     - ./data/certbot/www:/var/www/certbot      