version: "3.2"
services:
  apache:
    container_name: apache
    build: './apache/'
    ports: 
      - "8080:80" # "the order is Host:Container "
    volumes:
      - ./andy-yao.com/output:/var/www/andy-yao.com/build